name: Fork Sync

on:
  schedule:
    - cron: '30 */6 * * *' # every 3:00AM of every day

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3.0
        with:
          github_token: 4fda783e5672a2d9dbf96de93bf0e4d0d6d9af55
          owner: djfye
          base: dev
          head: dev
          pr_title: Merge
