name: Fork Sync

on:
  schedule:
    - cron: '30 */6 * * *' # 30th minute of every 6th hour every day

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3.0
        with:
          github_token: ${{ secrets.API_TOLKEN }}
          owner: djfye
          base: dev
          head: dev
          pr_title: Merge
