name: Fork Sync

on:
  schedule:
  - cron: '30 */6 * * *' # 30th minute of every 6 hours every day
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "nightscout/cgm-remote-monitor"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: "true"
        github_token: ${{ secrets.PERSONAL_TOKEN }}
